### ISSUE TITLE
navigateInfo vs. info

### ISSUE THREAD

**Issue by domenic** [WICG/app-history#134]
The `info` property on the `AppHistoryNavigateEvent` object [is cool](https://github.com/WICG/app-history#example-using-navigateinfo).

However currently you populate it via calls like

```js
appHistory.navigate(url, { navigateInfo: x });
appHistory.reload({ navigateInfo: x });
appHistory.goTo(key, { navigateInfo: x });
appHistory.back({ navigateInfo: x });
appHistory.forward({ navigateInfo: x });
```

Should this instead just be

```js
appHistory.navigate(url, { info: x });
appHistory.reload({ info: x });
appHistory.goTo(key, { info: x });
appHistory.back({ info: x });
appHistory.forward({ info: x });
```

?

The reasoning behind the current `navigateInfo` name is to make it clear the purpose is to feed into the `navigate` event. It's not something more interesting or persistent like the `state` or `replace` options. However, maybe this isn't that important...

**Comment by tbondwilkinson** [comment]
I also vote in favor of just "info"

Since we have an `appHistory.navigate` function as well, I did feel a little confused about in what conditions the "navigateInfo" would apply. Keeping it just "info" works for me.

In our history code we call this parameter "source" because it's usually used to pass along originating information, but we also have a "metadata" parameter. Info is fine though.

**Comment by dvoytenko** [comment]
+1 for `info`
