### ISSUE TITLE
Expanding examples and available information for currententrychange

### ISSUE THREAD

**Issue by domenic** [WICG/app-history#14]
(Moved from https://github.com/slightlyoff/history_api/issues/24 by @SetTrend and https://github.com/slightlyoff/history_api/pull/30 by @matt-buland-sfdc; summarized and synthesized by me.)

The proposal's current [`currententrychange` section](https://github.com/WICG/app-history#current-entry-change-monitoring) only has one weak example, around measuring navigation time. But since it's meant as a replacement for some subset of what people use `popstate` for today, we should expand it with others. @matt-buland-sfdc suggests:

> - change the page/content being shown based on the newly accepted location
>  - especially for handling browser-back
> - show side-bar content relevant to the current page (e.g. help items in the current page, etc)

and @SetTrend suggests that examples like these could be done more easily if the event had a pointer to the previous entry; his code is

```js
appHistory.addEventListener("currententrychange", e => {
  let diff = e.currentEntry.state.listItems.length - e.previousEntry.state.listItems.length;

  document.getElementById("result").innerText = `${Math.Abs(diff)} items have been ${diff < 0 ? "removed" : "added"}`;
});
```

**Comment by domenic** [comment]
I'm coming back to this and still struggling a bit. All of the cases described in the OP seem like they should be done in the `navigate` event; i.e., as part of intercepting the navigation and converting it to a single-page navigation, you should do your (possibly async) page-updating there. What role does that leave for `currentchange`?

It still feels like such an event should probably exist; changing something so central as `appHistory.current` seems like something you should be notified about! But I just can't find a use case. So I'll tag this as "feedback wanted", and if we can't find any use cases, maybe we should delete it.

**Comment by matt-buland-sfdc** [comment]
The issue with updating the page in `navigate` is that hook doesn't get invoked upon historical navigations (e.g. browser back to a location in the SPA's domain). Unless you're suggesting folks implement `oncurrententrychange => navigate('.')`. Reacting to historical navigations via popstate has been a struggle for us, and `currententrychange` mostly resolves them, which can demonstrate a big benefit to others as well. My original ask was to identify "what are the best practices for maintaining and reacting to navigations to previous (historical) entries?"

**Comment by domenic** [comment]
> is that hook doesn't get invoked upon historical navigations (e.g. browser back to a location in the SPA's domain).

It does.

**Comment by matt-buland-sfdc** [comment]
Ohhhh. Well that clears it up for me. That changes my perspective on currententrychange a bit then: Unlike `navigate`, `currententrychange` is just a notification that the browser has completed the URL change. With the suggestion to place critical logic in `navigate`, then non-critical logic could be placed in `currententrychange` (like the analytics example). 

I also agree with your statement: 
> It still feels like such an event should probably exist

IMO, this is because the browser is doing something that can impact the SPA. Only after this event, `<a href="./relative" >` and `window.location.href` are in sync with what the logic in `navigate` has assumed. If we had a `navigate` without the `currententrychange` occuring, the app could have a mismatch between content & URL.
