### ISSUE TITLE
Determining a history entry's origin

### ISSUE THREAD

**Issue by jakearchibald** [WICG/app-history#166]
Currently the spec adds an "origin" to history entries, but it feels like this could be determined from other things.

For `about:blank` and `about:srcdoc` pages, I'm going to create an "HTML resource" which has a source and an origin. This will go in the document state of the history entry.

For everything else, I think the URL of the history entry is enough to calculate the origin.

I think this would solve a couple of bugs in the current model. For example, take this history timeline: 

<img width="491" alt="Screenshot 2021-09-09 at 15 15 52" src="https://user-images.githubusercontent.com/93594/132702587-a56e520c-fe26-4696-b0f2-cbe0117fac4d.png">

Let's say the user presses back and the page comes from bfcache. Then they hit reload, but it fails as they're offline. Then they hit back again and the page comes from bfcache. So:

<img width="489" alt="Screenshot 2021-09-09 at 15 17 38" src="https://user-images.githubusercontent.com/93594/132702923-cdc43460-5eb5-4ca6-8ece-e9f45bbb0192.png">

It feels like the page should be able to see both forward history entries. However, the current model updates the origin when  "update the session history with the new page" is called, but that also happens for error documents, which would set the origin of the 2nd entry to an opaque origin. This wouldn't be an issue if the URL was used to determine the origin.

Another example:

<img width="489" alt="Screenshot 2021-09-09 at 15 24 20" src="https://user-images.githubusercontent.com/93594/132704096-6488b32f-7b03-46b8-8caa-b4e16be75d22.png">

(note the different origins)

Let's say the user presses back and the page comes from bfcache. Then they hit reload. This time it redirects to `//origin1/b`, but that page fails to load due to a DNS failure or whatever. Then they hit back again and the page comes from bfcache. So:

<img width="490" alt="Screenshot 2021-09-09 at 15 28 22" src="https://user-images.githubusercontent.com/93594/132704727-6f8ffbea-a1a1-496f-9aee-b17c0076c44e.png">

In this case I think the page should see one forward history entry. Although a document from that origin never successfully loaded, the history entry url origin is `origin1`. In the current model it would be an opaque origin.

cc @annevk since we talked about this on Matrix.

**Comment by jakearchibald** [comment]
Sandboxing is a complicating factor here I guess. So maybe we do need an origin, but it needs to be set on redirect, and on document creation, _unless_ the document is an error document.

**Comment by jakearchibald** [comment]
<img width="491" alt="Screenshot 2021-09-24 at 11 48 04" src="https://user-images.githubusercontent.com/93594/134662706-ee8c4d1f-cfb6-4a37-8516-44ceabaec67f.png">

In this case, step 2 loaded with `Content-Security-Policy: sandbox`. Can the document in step 1 see history entries for step 2 and 3? Does this matter if the documents are still alive or not?

**Comment by jakearchibald** [comment]
@domenic this might be another case where error documents are 'special'.

**Comment by domenic** [comment]
Marking as "might block v1" since the questions around whether error documents and sandbox should cut off access are potentially compat-sensitive. (We could probably get away with changing them after shipping, but it'd be better if we didn't have to.)

**Comment by annevk** [comment]
Given that per #167 opaque origins do not have access, I think the main question here is whether these URLs end up being a secret due to being sandboxed or an error page. I'd be inclined to say that's not the case.

There are use cases for capability URLs though and I'm not sure if we have a feature yet that would allow those pages to exclude themselves from this API. (This also came up in the context of the COOP+COEP integration discussion.)

**Comment by domenic** [comment]
Upon reflection I think it's just clearly simpler to stick with the current spec, which cuts off access to pages 2 and 3 in Jake's example from https://github.com/WICG/app-history/issues/166#issuecomment-926531747. The rule is simple: same-origin contiguous.

And, precisely because sandboxing, the [session history rewrite](https://github.com/whatwg/html/pull/6315) does preserve the origin in the session history entry.

So all that remains is to write some tests for this case, which I'll track with a Chromium bug.
