### ISSUE TITLE
Do opaque origins have access to the API

### ISSUE THREAD

**Issue by annevk** [WICG/app-history#167]
Related to #166, I wonder what kind of view we want to offer to opaque origins. Especially given that it seems we mainly want to disable storage APIs in them.

You could conceivably have multiple entries by having an opaque origin document create a blob URL and then navigate to that. Those would be same origin in principle. (This would be the first time that would be observable though, which kinda makes me think we shouldn't support it unless there's a use case.)

**Comment by annevk** [comment]
Jake pointed out that there are multiple things an opaque origin can do to end up with multiple entries, such as fragment navigations or using `history.pushState()`. It's not clear that makes it enough to offer this API, as this would give it for multiple documents as well. I think I'd rather start out by not providing this initially and offering it once we have a clear use case and demand.

**Comment by jakearchibald** [comment]
I thought it might have already been possible to create multiple history entries with an opaque origin and multiple documents, in Firefox at least:

1. Navigate to `data:text/html;charset=utf-8,%3Cp%3Ehello%3C%2Fp%3E`
1. `location.href = 'javascript:"hello"'`

But Firefox logs a warning: Navigation to toplevel data: URI not allowed (Blocked loading of: “data:text/html;charset=utf-8,<p>hello</p%3...”)

I don't think this behaviour is spec'd though.

Allowing history entries to have different documents but the same opaque origins could create problems though, since opaque origins aren't serialisable.

However, I don't think it's possible with apphistory to create multiple entries that have the same opaque origin but different documents.

**Comment by domenic** [comment]
I'm OK with restricting this until we have some clear demand. In particular I think we should follow similar restrictions to what we're imposing for the initial about:blank:

- No `navigate` events fire
- `appHistory.entries()` returns an empty array
- `appHistory.canGoBack`/`appHistory.canGoForward` are false.
- `appHistory.current` and `appHistory.transition` are null
- `appHistory.updateCurrent()` throws
- `appHistory.goTo()`/`appHistory.back()`/`appHistory.forward()` throw
- But, `appHistory.navigate()` and `appHistory.reload()` work fine
