### ISSUE TITLE
Adding sugar for current index/can go back/can go forward

### ISSUE THREAD

**Issue by domenic** [WICG/app-history#6]
(Moved from https://github.com/slightlyoff/history_api/issues/25 by @SetTrend, summarized by me.)

It's currently slightly awkward to determine the index of the current entry, and whether you can go back and forward:

```js
const index = appHistory.entries.indexOf(appHistory.currentEntry);
const canGoBack = index !== 0;
const canGoForward = index < appHistory.entries.length - 1;
```

It might be nice if this could be done with

```js
appHistory.currentIndex; // just index? or currentEntryIndex?
appHistory.canGoBack;
appHistory.canGoForward;
```

or maybe we should add something to all the individual entries, like

```js
appHistory.currentEntry.index;
appHistory.currentEntry.canGoBack; // isFirst?
appHistory.currentEntry.canGoForward; // isLast?
```

A use case where this is especially important is when you want to show your own navigation UI, such as when you're a widget inside an iframe (where the browser navigation UI is not very related to your UI). @SetTrend's specific example was a multi-step form embedded in an iframe.

**Comment by tbondwilkinson** [comment]
I do think we should add `index` to Entry. But I don't think we need `canGoBack` and `canGoForward`.

```js
const canGoBack = appHistory.currentEntry.index !== 0;
const canGoForward = appHistory.currentEntry.index < appHistory.entries.length -1;
```

Seems very reasonable to me, once we've added index to entries.

**Comment by SetTrend** [comment]
From discussion @ [slightlyoff/history_api#25](https://github.com/slightlyoff/history_api/issues/25):
>  it'll always contain the current entry, so it'll be of length 1.

I don't quite get the notion of a "current entry" in history.

1. Why is there always at least one entry in the collection?
1. What does the _current_ entry represent?
1. Shouldn't the _current_ entry be mutable?

**Comment by domenic** [comment]
> Why is there always at least one entry in the collection?

Because you are always on a page. That page is the current entry. To have zero entries, you'd need to not be on a page, but then you wouldn't be able to run JavaScript.

> What does the current entry represent?

The page you are on.

> Shouldn't the current entry be mutable?

It's not clear exactly what you mean by this.

**Comment by domenic** [comment]
> But I don't think we need canGoBack and canGoForward.

Although it's pretty straightforward, I find the lack of symmetry in

```js
if (appHistory.current.index !== 0) {
  await appHistory.back();
}
```

a bit displeasing.

```js
if (appHistory.canGoBack) {
  await appHistory.back();
}
```

seems nicer to me...

**Comment by SetTrend** [comment]
You know, I'm asking because ...

If the _current_ entry represents the _current_ page,  then a design may choose to use the `appHistory` current entry state for its view model state and incrementally update the object members of the `appHistory` current entry state to reflect the current situation.

![ViewState](https://user-images.githubusercontent.com/9283914/107851120-d0181e00-6e07-11eb-9fb5-d4cc4eee4496.png)


So, instead of storing the state somewhere else and clone it in order to add it to the history using `appHistory.update({ state })`, it could just use `appHistory.current.state` directly for it's view model state.

However, a deep clone operation is required anyway when calling `appHistory.update({ state })`, because otherwise, the application would accidentally update a previous history entry's state members.

That's why I'm asking about the notion of the current entry.

- Should there be an automatic deep clone operation involved with `appHistory.update({ state });`?
- How can a JavaScript be prevented from altering a previous entry's state object's members?

**Comment by domenic** [comment]
You may enjoy #17.

**Comment by domenic** [comment]
Minor question: if your `AppHistoryEntry` got disposed, should its `index` be `-1` or `null`?

Similarly, if you're looking at the `event.destination` `AppHistoryEntry` in a `navigate` event, should its index be `-1` or `null` or should it not exist as a property at all? (The latter would require using a different class than `AppHistoryEntry` but that's potentially a good idea for other reasons anyway.)
