### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by annevk** [WICG/app-history#83]
I'm somewhat hesitant to raise this bikeshed, but https://github.com/WICG/app-history/issues/82#issuecomment-802941987 made me think it. Should it be named `appHistory`?

Perhaps `appSession` would reflect things a tiny bit better? (I guess the one potential confusing thing here is that it's not 1:1 with `sessionStorage`, but `appHistory` is not 1:1 with `history` either.)

**Comment by domenic** [comment]
Yeah, app history is more of a "least bad" name. The predecessor proposal was called "navigator" and lived on `window.history.navigator`, but I thought that was pretty confusing.

"Session" seems like it might be the right spec-level concept to encompass "history and navigation", but it feels like the wrong web-dev-facing concept. When web devs talk about "sessions" it's mostly about user sessions, being logged in and out, etc., and not about history and navigation.

Between "history" and "navigation" I think most of the complexity (for web developers) comes in with history, so that's why I went with `window.appHistory` instead of `window.appNavigator` or `window.historyAndNavigation` or something. That does lead to confusion like https://github.com/WICG/app-history/issues/82#issuecomment-802941987 but that seems like an OK-ish price...

I'm happy to leave this open in case we come up with something brilliant. But my instincts are to stick with the inertia behind the current name, despite it not being perfect.

**Comment by kidwm** [comment]
How about `window.navigator.navigation` or `window.navigator.history`?

**Comment by kenchris** [comment]
navigationHistory?

**Comment by tbondwilkinson** [comment]
- `appSession`: For me this is confusing, because it doesn't necessarily indicate it has to do with history or navigation or the URL, which are things that I think of when I think of this API.
- `window.navigator.navigation` and `window.navigator.history`: I'm shaking my fist at the folks who got to `navigator`, because I think it has more to do with the User Agent than "navigation." But given that the existing `window.navigator` has little to do with navigation or history, I don't think it's right to hang this new API off that object.
- `navigationHistory`: I think this is largely equivalent to `appHistory`, but not better.
- `navigationStack`: People have quibbled about whether history is in fact a 'stack' (technically from a data structure POV, it's not), so I think I'd like to get away from this nomenclature.

**Comment by kenchris** [comment]
in appHistory, I am not sure what value "app" provides :-) at least "navigation history" provides a bit more clarification

**Comment by tbondwilkinson** [comment]
Well, I suppose the "app" part is signifying to importance of same-origin history for this API - most of the new functionality has to do with enabling an "app" to inspect and modify its own history. So I'm not totally opposed to "app" being in the name.

But I do agree that if I had to pick one word to represent all this, it would be "navigation". Navigation to me represents the action that the API enables, "history" represents the state left behind by that action. 

Not to throw another wrench, but other good words: "page", "view," "site". For instance, pageHistory (or pageNavigation), as opposed to appHistory, if no one likes the word app.

**Comment by Yay295** [comment]
In that case it would be `siteHistory`, not `pageHistory`. A website can be composed of many webpages.

**Comment by uasan** [comment]
Better - ```window.navigator.router```

**Comment by domenic** [comment]
@jakearchibald, @annevk, @smaug---- and I discussed this today. @smaug---- especially was of the opinion that this API is largely about navigation, and less so history. We tentatively thought that maybe just the name `window.navigation` (and spec title "Navigation API") would work:

```js
await navigation.navigate(url);

const entries = navigation.entries();
const currentEntry = navigation.current; // or currentEntry? or now?

await navigation.transition.finished;

await navigation.back();
await navigation.goTo(key);
```

This seems pretty OK to me. What do other folks think?

**Comment by frehner** [comment]
I like it. 

Are there any chances of library/global conflicts? I tried doing some searching to see if anything puts `navigation` onto global/window but at first glance couldn't find anything.

**Comment by domenic** [comment]
It's always hard to say, but generally on the web platform we haven't had many such conflicts. (The only one I'm aware of is when TC39 tried to introduce `global`, resulting in the current `globalThis` name.) We could also minimize the risk by making the global [`[Replaceable]`](https://heycam.github.io/webidl/#Replaceable).

**Comment by bathos** [comment]
Navigation is not a bad name, though it seem a lot more natural to call the-stateful-thing-you-call-navigate-on navigator, which — oh, wait, it seems that’s taken? perhaps this is not such a good name. :)

Can’t say I would look forward much to mistyping and misreading this all the time, and I’m a native speaker, so it may be more troublesome for others. AppHistory seemed fine to me — FWIW, the moment I saw that name, I knew what it was gonna be about, though I couldn’t nec explain why?

Of course this won’t make or break it but I do hope folks land on anything-but-navigation (because of navigator I mean — it seems fine conceptually).

**Comment by Yay295** [comment]
Unfortunately, I agree that "Navigation" may be too similar to the existing Navigator object (which ironically doesn't seem to have much to do with navigating). Perhaps "ApplicationState"?

**Comment by uasan** [comment]
Maybe - window.navigator.app?

**Comment by jakearchibald** [comment]
I'd be happy with `navigation` or just `nav`. But in case we need another option:

Aside from just being better in a number of ways, there are two restrictions `appHistory` has vs `history`:

- The exposed history is for the current frame only
- The exposed history is limited to the current origin, contiguously

Based on that, there still isn't a name that jumps out at me, but here goes:

- `frameHistory`/`frameNav`/`frameNavigation` - since the history is related to the frame. But, maybe frames sounds old and horrible, and it isn't clear that the top level is also a frame of sorts?
- `navigableHistory`/`navHistory` - Assuming 'navigable' is a term we land on for "a thing that can be navigated".
- `originHistory` - Although this doesn't make it clear that entries are limited to this navigable.

**Comment by bathos** [comment]
Spitballing in case one of these clicks with people or, more likely, serves as a prompt.

- Traverser
- Traveller
- BrowserNav
- BrowserTimeline
- Annals
- Herstory
- Historiographer
- [Ziggy](https://en.wikipedia.org/wiki/List_of_Quantum_Leap_characters#Ziggy)

To be safe I’m not gonna make any claim about which of these are jokes and which I actually think are potentially good. If you hate them all, then they’re all jokes :)

**Comment by bathos** [comment]
Placing this on the radar if it’s not already: the currently unqualified/unprefixed use of "navigate"/"nav" in global interface, operation, and event names in [CSS Spatial Navigation](https://drafts.csswg.org/css-nav-1/) proposal.

https://github.com/w3c/csswg-drafts/issues/3387#issuecomment-890411270

**Comment by domenic** [comment]
Hey everyone,

After a half-year with no particularly better ideas, and a bit more offline discussion with @annevk and @smaug----, we think `window.navigation` is the best name on offer. This API really is about navigation, which encompasses history. All the other alternatives, e.g. variants on "history" or "traversal", fail to capture this scope.

The way in which the name starts with the same seven characters as `navigator` is unfortunate, but we think it'll be survivable.

This issue will remain open to track renaming everything (which will be fun :grimacing:).

**Comment by domenic** [comment]
I'm working on a draft spec PR, but I want to get some any feedback on the details of the rename as early as possible.

#### Noticeable developer-visible renames

* `window.appHistory` → `window.navigation`
* `appHistory.current` → `navigation.currentEntry`
  * `currentchange` event → `currententrychange` event
  * `updateCurrent()` → `updateCurrentEntry()`
* `appHistory.goTo()` → `navigation.traverseTo()`

#### Class name changes

These are mostly not developer-impacting in mainstream code scenarios, but can impact e.g. feature detection. So we can make them longer and uglier if we want, e.g. we could add a bunch of `NavigationAPI` prefixes. (Although the "API" part doesn't have any precedent on the web platform, so probably not that.)

We should avoid changing them after shipping.

* `AppHistory` → `Navigation`
* `AppHistoryTransition` → `NavigationTransition`
* `AppHistoryEntry` → `HistoryEntry`
* `AppHistoryCurrentChangeEvent` → `CurrentHistoryEntryChangeEvent`
* `AppHistoryNavigateEvent` → `NavigateEvent`
* `AppHistoryDestination` → `NavigationDestination`

#### Not-exposed IDL name changes

These names, for dictionaries and enums, are not something developers have any insight into and the only concern is clarity for the spec ecosystem, and avoiding collisions across the spec ecosystem. We can change them at any time.

* `AppHistoryUpdateCurrentOptions` → `UpdateCurrentHistoryEntryOptions`
* `AppHistoryNavigationOptions` → `NavigationOptions`
* `AppHistoryNavigateOptions` → `NavigateOptions`
* `AppHistoryReloadOptions` → `ReloadOptions`
* `AppHistoryResult` → `NavigationResult`
* `AppHistoryNavigationType` → `NavigationAPINavigationType` (I would like this to be `NavigationType`; depends on https://github.com/w3c/navigation-timing/pull/172)

**Comment by frehner** [comment]
>AppHistoryEntry → HistoryEntry
>AppHistoryCurrentChangeEvent → CurrentHistoryEntryChangeEvent

It seems a little strange to me that these don't have the word `navigation` in them and everything else developer-facing does. I also like the idea of having navigation in the name to help direct people what it's associated with.

>AppHistoryUpdateCurrentOptions → UpdateCurrentHistoryEntryOptions
>AppHistoryReloadOptions → ReloadOptions

Same here for these two, but maybe not as important because they're not dev-facing.

**Comment by domenic** [comment]
Yeah, fair point, let me do some updates...

**Comment by fabiancook** [comment]
New name looks & works great, have updated all the names used in my implementation here:  https://github.com/virtualstate/navigation#navigation, wasn't too hard of a task replacing everything with that concise list above 😛 

Whats the next steps for chromium's adoption of the name change, followed by web platform tests? If I/someone were to submit a PR of all the same name changes from the above list to wpt, how long does it usually take for something like this to make it into some builds of chromium?

**Comment by domenic** [comment]
>> Are there any chances of library/global conflicts? I tried doing some searching to see if anything puts `navigation` onto global/window but at first glance couldn't find anything.
>
> It's always hard to say, but generally on the web platform we haven't had many such conflicts. (The only one I'm aware of is when TC39 tried to introduce `global`, resulting in the current `globalThis` name.) We could also minimize the risk by making the global [`[Replaceable]`](https://heycam.github.io/webidl/#Replaceable).

It turns out this is necessary, or at least, necessary for making [some of Chromium's internal tests](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/http/tests/misc/webtiming-no-origin.html;l=13;drc=77578ccb4082ae20a9326d9e673225f1189ebb63) pass. (And those tests are probably reasonably representative of some real code; `var navigation = stuff` in classic `<script>`s is probably a thing that happens.)

I guess a difference between `fetch` and `navigation` is that `fetch` is a data property, and thus doesn't counter this problem, whereas `navigation` is a getter.

I'll update the spec momentarily.

**Comment by ljharb** [comment]
Also any HTML element with an ID of “navigation” would create a JS global that might be referenced; that happened with “global” as well.

**Comment by domenic** [comment]
Is everyone OK with renaming `goTo()` to `traverseTo()`, coupled with leaving `canGoBack`/`canGoForward` as-is? I think it's OK but @natechapin pointed out that maybe we should use the same verb in both. E.g. `canTraverseBack`.

**Comment by ljharb** [comment]
traverse is a longer and harder wordto spell, especially for non-native English speakers; what’s wrong with goTo?

**Comment by domenic** [comment]
`navigation.goTo()` sounds like it would navigate ("go") to the argument.

**Comment by ljharb** [comment]
Clearly I’ve missed context :-) traverse is a synonym to go; they imply the same to me. What does it actually do?

**Comment by bathos** [comment]
@ljharb My understanding is that "traversal", at least in the context of HTML navigation,  is used specifically to describe navigations whose destination is an existing entry. I don't know if I'd find that intuitive / inferable from the word alone either, though, since this is something that's already been in my head too long.

**Comment by ljharb** [comment]
It's navigating there regardless; it just might not trigger a page load. What does `traverseTo` do when it's not an existing entry?

**Comment by bathos** [comment]
> What does traverseTo do when it's not an existing entry?

If the key (string) doesn't identify an existing entry, it ends up rejected with an [InvalidStateError DOMException](https://wicg.github.io/navigation-api/#dom-navigation-traverseto).

**Comment by Yay295** [comment]
What about `loadEntry` then?

**Comment by domenic** [comment]
These are not correct ways to think about traversal... We're pretty happy with the name `traverseTo()`. I don't plan on changing it, but I do urge people who aren't familiar with navigation/traversal to read through the relevant specs and documentation.

**Comment by annevk** [comment]
@natechapin's suggestion makes sense to me. It's not immediately clear how you'd otherwise tell that these fields are related.

**Comment by domenic** [comment]
Well, I was hoping it was clear that `canGoBack` was related to `back()` via the "back" part...
